/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf 
Author: Sm1yle (https://sketchfab.com/Sm1yle)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pizza-75c70d6782814bb5857b52b91241ce25
Title: Pizza
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.003']} position={[-0.02, -0.011, 0.684]} scale={0.401} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.001']} position={[-0.02, -0.011, 0.684]} scale={0.401} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['Material.001']} position={[0.115, 0.003, 0.765]} scale={[0.038, 0.004, 0.038]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['Material.001']} position={[0.012, 0.003, 0.871]} scale={[0.038, 0.004, 0.038]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials['Material.001']} position={[0.206, 0.003, 0.878]} scale={[0.038, 0.004, 0.038]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials['Material.001']} position={[0.27, 0.003, 0.78]} scale={[0.038, 0.004, 0.038]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials['Material.001']} position={[0.227, 0.003, 0.643]} scale={[0.038, 0.004, 0.038]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials['Material.001']} position={[-0.206, 0.003, 0.698]} scale={[0.038, 0.004, 0.038]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials['Material.001']} position={[-0.316, 0.003, 0.761]} scale={[0.038, 0.004, 0.038]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials['Material.001']} position={[-0.265, 0.003, 0.866]} scale={[0.038, 0.004, 0.038]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials['Material.001']} position={[-0.11, 0.003, 0.982]} scale={[0.038, 0.004, 0.038]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials['Material.001']} position={[-0.11, 0.003, 0.779]} scale={[0.038, 0.004, 0.038]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials['Material.001']} position={[-0.115, 0.003, 0.563]} scale={[0.038, 0.004, 0.038]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials['Material.001']} position={[-0.255, 0.003, 0.561]} scale={[0.038, 0.004, 0.038]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials['Material.001']} position={[-0.233, 0.003, 0.43]} scale={[0.038, 0.004, 0.038]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials['Material.001']} position={[-0.11, 0.003, 0.396]} scale={[0.038, 0.004, 0.038]} />
      <mesh geometry={nodes.Object_36.geometry} material={materials['Material.001']} position={[0, 0.002, 0.377]} scale={[0.038, 0.004, 0.038]} />
      <mesh geometry={nodes.Object_38.geometry} material={materials['Material.001']} position={[0.055, 0.003, 0.492]} scale={[0.038, 0.004, 0.038]} />
      <mesh geometry={nodes.Object_40.geometry} material={materials['Material.001']} position={[0.168, 0.003, 0.419]} scale={[0.038, 0.004, 0.038]} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
